build-containerfile:
    sudo podman build -t libvirt-nspawn .

extract-rootfs:
    just terminate || echo "Already stopped, ignore error..."
    sudo rm -rf /var/lib/machines/nspawn-libvirt
    sudo mkdir -p /var/lib/machines/nspawn-libvirt
    sudo podman create --name nspawn-temp-build libvirt-nspawn
    sudo podman export nspawn-temp-build | sudo tar -C /var/lib/machines/nspawn-libvirt -xf -
    sudo podman rm nspawn-temp-build

run:
    sudo mkdir -p /var/run/libvirt-nspawn
    sudo systemd-nspawn -bD /var/lib/machines/nspawn-libvirt \
        --capability=CAP_NET_ADMIN,CAP_SYS_ADMIN \
        --property=Delegate=yes \
        --property=DeviceAllow='char-usb_device rwm' \
        --property=DeviceAllow='char-usb rwm' \
        --bind=/dev/bus/usb \
        --bind=/dev/net/tun \
        --bind=/dev/kvm \
        --bind=/var/run/libvirt-nspawn:/run/libvirt \
        --bind=/var/lib/libvirt/images:/var/lib/libvirt/images \
        --bind=/var/home/$USER/Downloads:/home/$USER/Downloads \
        --network-veth \
        --system-call-filter=@privileged

terminate:
    sudo machinectl terminate nspawn-libvirt

add-to-virtman-flatpak:
    sudo flatpak override --filesystem=/run/libvirt-nspawn:rw org.virt_manager.VirtManager
    flatpak run org.virt_manager.virt-manager -c "qemu+unix:///system?socket=/var/run/libvirt-nspawn/libvirt-sock"